"""update expo token in user

Revision ID: 508eb7b6704f
Revises: 9a8382e19985
Create Date: 2026-05-14 13:05:00.783804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508eb7b6704f'
down_revision: Union[str, Sequence[str], None] = '9a8382e19985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expo_push_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expo_push_token')
    # ### end Alembic commands ###
