"""add strain log

Revision ID: 7662ad40d297
Revises: d8fe93e16181
Create Date: 2026-05-11 03:04:51.363515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7662ad40d297'
down_revision: Union[str, Sequence[str], None] = 'd8fe93e16181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telemetry_id', sa.UUID(), nullable=False),
    sa.Column('strain_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('recovery_needed', sa.Boolean(), nullable=True),
    sa.Column('recovery_debt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strain_logs')
    # ### end Alembic commands ###
