"""create telemetry logs table

Revision ID: 8b91c38b5069
Revises: f2dc4edb0554
Create Date: 2026-05-10 17:17:15.652971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b91c38b5069'
down_revision: Union[str, Sequence[str], None] = 'f2dc4edb0554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('app_category', sa.String(), nullable=False),
    sa.Column('screen_on_minutes', sa.Integer(), nullable=False),
    sa.Column('continuous_focus_minutes', sa.Integer(), nullable=False),
    sa.Column('brightness_level', sa.Integer(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_logs')
    # ### end Alembic commands ###
