"""update_recovery_logs_nullable

Revision ID: 927dd5c5a5df
Revises: 7744db0eda0a
Create Date: 2026-06-01 10:09:11.952495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '927dd5c5a5df'
down_revision: Union[str, Sequence[str], None] = '7744db0eda0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_logs', sa.Column('focal_isolation_session_id', sa.UUID(), nullable=True))
    op.alter_column('recovery_logs', 'regulation_session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'recovery_logs', 'focal_isolation_sessions', ['focal_isolation_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_logs', type_='foreignkey')
    op.alter_column('recovery_logs', 'regulation_session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('recovery_logs', 'focal_isolation_session_id')
    # ### end Alembic commands ###
