"""add regulation log

Revision ID: c0358a57a297
Revises: 5fdc66a4cea6
Create Date: 2026-05-11 03:22:37.941294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0358a57a297'
down_revision: Union[str, Sequence[str], None] = '5fdc66a4cea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_sessions', sa.Column('strain_log_id', sa.UUID(), nullable=True))
    op.add_column('regulation_sessions', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('regulation_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('regulation_sessions', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'regulation_sessions', 'strain_logs', ['strain_log_id'], ['id'])
    op.drop_column('regulation_sessions', 'started_at')
    op.drop_column('regulation_sessions', 'ended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_sessions', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('regulation_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'regulation_sessions', type_='foreignkey')
    op.alter_column('regulation_sessions', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('regulation_sessions', 'created_at')
    op.drop_column('regulation_sessions', 'completed')
    op.drop_column('regulation_sessions', 'strain_log_id')
    # ### end Alembic commands ###
