"""add recovery log

Revision ID: e88a43076b4a
Revises: c0358a57a297
Create Date: 2026-05-11 03:35:05.991241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88a43076b4a'
down_revision: Union[str, Sequence[str], None] = 'c0358a57a297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('regulation_session_id', sa.UUID(), nullable=False),
    sa.Column('pre_strain_score', sa.Integer(), nullable=False),
    sa.Column('post_strain_score', sa.Integer(), nullable=False),
    sa.Column('recovery_delta', sa.Integer(), nullable=False),
    sa.Column('recovery_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['regulation_session_id'], ['regulation_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_logs')
    # ### end Alembic commands ###
